config/routes.rb
Rails.application.routes.draw do
  root to: 'contracts#index'

  resources :contracts

  resources :attachments, only: %i[create]

  resources :direct_file_uploads, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true

  has_attached_file :upload,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    path: ':tenant_directory/:class/:attachment/:hash/:style/:filename',
                    hash_data: ':id/:extension/:fingerprint/:updated_at'

  validates_attachment :upload,
                       presence: true,
                       content_type: { content_type: %w[image/png] },
                       size: { in: 0..100.megabytes }

  # custom interpolation :tenant_directory
  # refer to: config/initializers/paperclip.rb
  def tenant_directory
    'tenant_identifier' # customize with your own multi-tenancy strategy
  end
end

app/models/contract.rb
class Contract < ApplicationRecord
  has_many :attachments, as: :attachable, dependent: :restrict_with_error

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # POST /attachments
  def create
    @attachment = Attachment.new(attachment_params)

    ::Services::DirectFileUpload.prepare_attachment(
      paperclip_attachment: @attachment.upload,
      upload_key:           params[:upload_key]
    )

    if @attachment.save
      render json: @attachment, status: :created
    else
      render json: @attachment.errors, status: :unprocessable_entity
    end
  end

  private
  def attachment_params
    params.require(:attachment).permit(:attachable_type, :attachable_id)
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: %i[ show edit update destroy ]

  # GET /contracts or /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1 or /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts or /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: "Contract was successfully created." }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1 or /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: "Contract was successfully updated." }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1 or /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: "Contract was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:name)
    end
end

app/controllers/direct_file_uploads_controller.rb
class DirectFileUploadsController < ApplicationController
  # POST /direct_file_uploads
  def create
    presigned_url_settings =
      ::Services::DirectFileUpload.create_presigned_url(
        file_params: params[:file]
      )

    render json: presigned_url_settings, status: :created
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/attachments/_form_for_attachable.html.erb
<%= javascript_pack_tag 'direct_file_upload' %>

<%= form_with model: attachable.attachments.build, local: true, html: { data: { direct_file_upload: true } } do |form| %>
  <%= form.hidden_field :attachable_type %>
  <%= form.hidden_field :attachable_id %>
  <%= form.file_field :upload, multiple: true %>
  <%= form.submit %>
<% end %>

app/views/attachments/_index_for_attachable.html.erb
<h3>Documents</h3>

<table>
  <thead>
    <tr>
      <th>File Name</th>
      <th>File Size</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% attachable.attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.upload_file_name %></td>
        <td><%= number_to_human_size(attachment.upload_file_size) %></td>
        <td><%= link_to 'Download', attachment.upload.expiring_url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contracts/_form.html.erb
<%= form_with(model: contract) do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
        <% contract.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.name %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contract.name %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

<hr>

<%= render partial: 'attachments/index_for_attachable', locals: { attachable: @contract } %>
<%= render partial: 'attachments/form_for_attachable', locals: { attachable: @contract } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Direct File Upload With Paperclip and S3-compatible Object Storage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>